-- Canonical schema: ../lib/db/schema.ts
-- Initial production migration: ./migrations/0000_initial_auth_rbac.sql
--
-- Do not maintain a second handwritten schema in this file. Generate reviewed
-- SQL with `npm run db:generate`, apply it with `npm run db:migrate`, and keep
-- every migration under version control so database changes remain auditable.
